{
  "os": "linux",
  "php": "7.0",
  "dist": "trusty",
  "group": "stable",
  "install": [
    "composer install",
    "cp .env.travis .env",
    "touch database/database.testing",
    "php artisan key:generate",
    "php artisan migrate --seed"
  ],
  "language": "php"
}